# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqt_filter_new.ui'
#
# Created: Thu May 31 23:10:53 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1124, 691)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.quickFrame = QtGui.QFrame(self.centralwidget)
        self.quickFrame.setMinimumSize(QtCore.QSize(180, 200))
        self.quickFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.quickFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.quickFrame.setObjectName(_fromUtf8("quickFrame"))
        self.responseBox = QtGui.QGroupBox(self.quickFrame)
        self.responseBox.setGeometry(QtCore.QRect(10, 10, 161, 251))
        self.responseBox.setObjectName(_fromUtf8("responseBox"))
        self.checkOverlaymode = QtGui.QCheckBox(self.responseBox)
        self.checkOverlaymode.setGeometry(QtCore.QRect(10, 20, 151, 19))
        self.checkOverlaymode.setChecked(True)
        self.checkOverlaymode.setObjectName(_fromUtf8("checkOverlaymode"))
        self.checkMagres = QtGui.QCheckBox(self.responseBox)
        self.checkMagres.setGeometry(QtCore.QRect(10, 40, 151, 19))
        self.checkMagres.setChecked(True)
        self.checkMagres.setObjectName(_fromUtf8("checkMagres"))
        self.checkPhase = QtGui.QCheckBox(self.responseBox)
        self.checkPhase.setGeometry(QtCore.QRect(10, 60, 151, 19))
        self.checkPhase.setChecked(True)
        self.checkPhase.setObjectName(_fromUtf8("checkPhase"))
        self.checkGdelay = QtGui.QCheckBox(self.responseBox)
        self.checkGdelay.setGeometry(QtCore.QRect(10, 80, 111, 19))
        self.checkGdelay.setChecked(True)
        self.checkGdelay.setObjectName(_fromUtf8("checkGdelay"))
        self.checkPdelay = QtGui.QCheckBox(self.responseBox)
        self.checkPdelay.setGeometry(QtCore.QRect(10, 100, 111, 19))
        self.checkPdelay.setObjectName(_fromUtf8("checkPdelay"))
        self.checkImpulse = QtGui.QCheckBox(self.responseBox)
        self.checkImpulse.setGeometry(QtCore.QRect(10, 120, 141, 19))
        self.checkImpulse.setObjectName(_fromUtf8("checkImpulse"))
        self.checkStep = QtGui.QCheckBox(self.responseBox)
        self.checkStep.setGeometry(QtCore.QRect(10, 140, 131, 19))
        self.checkStep.setObjectName(_fromUtf8("checkStep"))
        self.checkGrid = QtGui.QCheckBox(self.responseBox)
        self.checkGrid.setGeometry(QtCore.QRect(10, 160, 85, 19))
        self.checkGrid.setObjectName(_fromUtf8("checkGrid"))
        self.groupSpecs = QtGui.QGroupBox(self.quickFrame)
        self.groupSpecs.setGeometry(QtCore.QRect(10, 280, 161, 91))
        self.groupSpecs.setObjectName(_fromUtf8("groupSpecs"))
        self.checkBand = QtGui.QCheckBox(self.groupSpecs)
        self.checkBand.setGeometry(QtCore.QRect(10, 20, 85, 19))
        self.checkBand.setObjectName(_fromUtf8("checkBand"))
        self.checkPzplot = QtGui.QCheckBox(self.groupSpecs)
        self.checkPzplot.setGeometry(QtCore.QRect(10, 40, 131, 19))
        self.checkPzplot.setObjectName(_fromUtf8("checkPzplot"))
        self.checkFcoeff = QtGui.QCheckBox(self.groupSpecs)
        self.checkFcoeff.setGeometry(QtCore.QRect(10, 60, 131, 19))
        self.checkFcoeff.setObjectName(_fromUtf8("checkFcoeff"))
        self.gridLayout.addWidget(self.quickFrame, 0, 2, 1, 1)
        self.filterFrame = QtGui.QFrame(self.centralwidget)
        self.filterFrame.setMinimumSize(QtCore.QSize(300, 0))
        self.filterFrame.setMaximumSize(QtCore.QSize(300, 16777215))
        self.filterFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.filterFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.filterFrame.setObjectName(_fromUtf8("filterFrame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.filterFrame)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.comboBox = QtGui.QComboBox(self.filterFrame)
        self.comboBox.setEnabled(False)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.comboBox)
        self.filterTypeComboBox = QtGui.QComboBox(self.filterFrame)
        self.filterTypeComboBox.setObjectName(_fromUtf8("filterTypeComboBox"))
        self.filterTypeComboBox.addItem(_fromUtf8(""))
        self.filterTypeComboBox.addItem(_fromUtf8(""))
        self.filterTypeComboBox.addItem(_fromUtf8(""))
        self.filterTypeComboBox.addItem(_fromUtf8(""))
        self.filterTypeComboBox.addItem(_fromUtf8(""))
        self.filterTypeComboBox.addItem(_fromUtf8(""))
        self.filterTypeComboBox.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.filterTypeComboBox)
        self.filterDesignTypeComboBox = QtGui.QComboBox(self.filterFrame)
        self.filterDesignTypeComboBox.setObjectName(_fromUtf8("filterDesignTypeComboBox"))
        self.filterDesignTypeComboBox.addItem(_fromUtf8(""))
        self.filterDesignTypeComboBox.addItem(_fromUtf8(""))
        self.filterDesignTypeComboBox.addItem(_fromUtf8(""))
        self.filterDesignTypeComboBox.addItem(_fromUtf8(""))
        self.filterDesignTypeComboBox.addItem(_fromUtf8(""))
        self.filterDesignTypeComboBox.addItem(_fromUtf8(""))
        self.filterDesignTypeComboBox.addItem(_fromUtf8(""))
        self.verticalLayout.addWidget(self.filterDesignTypeComboBox)
        self.globalParamsLayout = QtGui.QFormLayout()
        self.globalParamsLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.globalParamsLayout.setObjectName(_fromUtf8("globalParamsLayout"))
        self.sampleRateLabel = QtGui.QLabel(self.filterFrame)
        self.sampleRateLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.sampleRateLabel.setObjectName(_fromUtf8("sampleRateLabel"))
        self.globalParamsLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.sampleRateLabel)
        self.sampleRateEdit = QtGui.QLineEdit(self.filterFrame)
        self.sampleRateEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        self.sampleRateEdit.setObjectName(_fromUtf8("sampleRateEdit"))
        self.globalParamsLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.sampleRateEdit)
        self.filterGainLabel = QtGui.QLabel(self.filterFrame)
        self.filterGainLabel.setObjectName(_fromUtf8("filterGainLabel"))
        self.globalParamsLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.filterGainLabel)
        self.filterGainEdit = QtGui.QLineEdit(self.filterFrame)
        self.filterGainEdit.setObjectName(_fromUtf8("filterGainEdit"))
        self.globalParamsLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.filterGainEdit)
        self.verticalLayout.addLayout(self.globalParamsLayout)
        self.filterTypeWidget = QtGui.QStackedWidget(self.filterFrame)
        self.filterTypeWidget.setObjectName(_fromUtf8("filterTypeWidget"))
        self.firlpfPage = QtGui.QWidget()
        self.firlpfPage.setObjectName(_fromUtf8("firlpfPage"))
        self.formLayout = QtGui.QFormLayout(self.firlpfPage)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.endofLpfPassBandLabel = QtGui.QLabel(self.firlpfPage)
        self.endofLpfPassBandLabel.setObjectName(_fromUtf8("endofLpfPassBandLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.endofLpfPassBandLabel)
        self.endofLpfPassBandEdit = QtGui.QLineEdit(self.firlpfPage)
        self.endofLpfPassBandEdit.setObjectName(_fromUtf8("endofLpfPassBandEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.endofLpfPassBandEdit)
        self.startofLpfStopBandLabel = QtGui.QLabel(self.firlpfPage)
        self.startofLpfStopBandLabel.setObjectName(_fromUtf8("startofLpfStopBandLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.startofLpfStopBandLabel)
        self.startofLpfStopBandEdit = QtGui.QLineEdit(self.firlpfPage)
        self.startofLpfStopBandEdit.setObjectName(_fromUtf8("startofLpfStopBandEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.startofLpfStopBandEdit)
        self.lpfStopBandAttenLabel = QtGui.QLabel(self.firlpfPage)
        self.lpfStopBandAttenLabel.setObjectName(_fromUtf8("lpfStopBandAttenLabel"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lpfStopBandAttenLabel)
        self.lpfStopBandAttenEdit = QtGui.QLineEdit(self.firlpfPage)
        self.lpfStopBandAttenEdit.setObjectName(_fromUtf8("lpfStopBandAttenEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lpfStopBandAttenEdit)
        self.lpfPassBandRippleEdit = QtGui.QLineEdit(self.firlpfPage)
        self.lpfPassBandRippleEdit.setObjectName(_fromUtf8("lpfPassBandRippleEdit"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lpfPassBandRippleEdit)
        self.lpfPassBandRippleLabel = QtGui.QLabel(self.firlpfPage)
        self.lpfPassBandRippleLabel.setObjectName(_fromUtf8("lpfPassBandRippleLabel"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.lpfPassBandRippleLabel)
        self.filterTypeWidget.addWidget(self.firlpfPage)
        self.firbpfPage = QtGui.QWidget()
        self.firbpfPage.setObjectName(_fromUtf8("firbpfPage"))
        self.formLayout_2 = QtGui.QFormLayout(self.firbpfPage)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.startofBpfPassBandLabel = QtGui.QLabel(self.firbpfPage)
        self.startofBpfPassBandLabel.setObjectName(_fromUtf8("startofBpfPassBandLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.startofBpfPassBandLabel)
        self.startofBpfPassBandEdit = QtGui.QLineEdit(self.firbpfPage)
        self.startofBpfPassBandEdit.setObjectName(_fromUtf8("startofBpfPassBandEdit"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.startofBpfPassBandEdit)
        self.endofBpfPassBandLabel = QtGui.QLabel(self.firbpfPage)
        self.endofBpfPassBandLabel.setObjectName(_fromUtf8("endofBpfPassBandLabel"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.endofBpfPassBandLabel)
        self.endofBpfPassBandEdit = QtGui.QLineEdit(self.firbpfPage)
        self.endofBpfPassBandEdit.setObjectName(_fromUtf8("endofBpfPassBandEdit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.endofBpfPassBandEdit)
        self.bpfStopBandAttenEdit = QtGui.QLineEdit(self.firbpfPage)
        self.bpfStopBandAttenEdit.setObjectName(_fromUtf8("bpfStopBandAttenEdit"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.bpfStopBandAttenEdit)
        self.bpfStopBandAttenLabel = QtGui.QLabel(self.firbpfPage)
        self.bpfStopBandAttenLabel.setObjectName(_fromUtf8("bpfStopBandAttenLabel"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.bpfStopBandAttenLabel)
        self.bpfTransitionLabel = QtGui.QLabel(self.firbpfPage)
        self.bpfTransitionLabel.setObjectName(_fromUtf8("bpfTransitionLabel"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.bpfTransitionLabel)
        self.bpfTransitionEdit = QtGui.QLineEdit(self.firbpfPage)
        self.bpfTransitionEdit.setObjectName(_fromUtf8("bpfTransitionEdit"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.bpfTransitionEdit)
        self.bpfPassBandRippleEdit = QtGui.QLineEdit(self.firbpfPage)
        self.bpfPassBandRippleEdit.setObjectName(_fromUtf8("bpfPassBandRippleEdit"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.bpfPassBandRippleEdit)
        self.bpfPassBandRippleLabel = QtGui.QLabel(self.firbpfPage)
        self.bpfPassBandRippleLabel.setObjectName(_fromUtf8("bpfPassBandRippleLabel"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.bpfPassBandRippleLabel)
        self.filterTypeWidget.addWidget(self.firbpfPage)
        self.firbnfPage = QtGui.QWidget()
        self.firbnfPage.setObjectName(_fromUtf8("firbnfPage"))
        self.formLayout_5 = QtGui.QFormLayout(self.firbnfPage)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.startofBnfStopBandLabel = QtGui.QLabel(self.firbnfPage)
        self.startofBnfStopBandLabel.setObjectName(_fromUtf8("startofBnfStopBandLabel"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.startofBnfStopBandLabel)
        self.startofBnfStopBandEdit = QtGui.QLineEdit(self.firbnfPage)
        self.startofBnfStopBandEdit.setObjectName(_fromUtf8("startofBnfStopBandEdit"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.startofBnfStopBandEdit)
        self.endofBnfStopBandLabel = QtGui.QLabel(self.firbnfPage)
        self.endofBnfStopBandLabel.setObjectName(_fromUtf8("endofBnfStopBandLabel"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.endofBnfStopBandLabel)
        self.endofBnfStopBandEdit = QtGui.QLineEdit(self.firbnfPage)
        self.endofBnfStopBandEdit.setObjectName(_fromUtf8("endofBnfStopBandEdit"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.endofBnfStopBandEdit)
        self.bnfTransitionLabel = QtGui.QLabel(self.firbnfPage)
        self.bnfTransitionLabel.setObjectName(_fromUtf8("bnfTransitionLabel"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.LabelRole, self.bnfTransitionLabel)
        self.bnfTransitionEdit = QtGui.QLineEdit(self.firbnfPage)
        self.bnfTransitionEdit.setObjectName(_fromUtf8("bnfTransitionEdit"))
        self.formLayout_5.setWidget(2, QtGui.QFormLayout.FieldRole, self.bnfTransitionEdit)
        self.bnfStopBandAttenLabel = QtGui.QLabel(self.firbnfPage)
        self.bnfStopBandAttenLabel.setObjectName(_fromUtf8("bnfStopBandAttenLabel"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.LabelRole, self.bnfStopBandAttenLabel)
        self.bnfStopBandAttenEdit = QtGui.QLineEdit(self.firbnfPage)
        self.bnfStopBandAttenEdit.setObjectName(_fromUtf8("bnfStopBandAttenEdit"))
        self.formLayout_5.setWidget(3, QtGui.QFormLayout.FieldRole, self.bnfStopBandAttenEdit)
        self.bnfPassBandRippleLabel = QtGui.QLabel(self.firbnfPage)
        self.bnfPassBandRippleLabel.setObjectName(_fromUtf8("bnfPassBandRippleLabel"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.LabelRole, self.bnfPassBandRippleLabel)
        self.bnfPassBandRippleEdit = QtGui.QLineEdit(self.firbnfPage)
        self.bnfPassBandRippleEdit.setObjectName(_fromUtf8("bnfPassBandRippleEdit"))
        self.formLayout_5.setWidget(4, QtGui.QFormLayout.FieldRole, self.bnfPassBandRippleEdit)
        self.filterTypeWidget.addWidget(self.firbnfPage)
        self.firhpfPage = QtGui.QWidget()
        self.firhpfPage.setObjectName(_fromUtf8("firhpfPage"))
        self.formLayout_3 = QtGui.QFormLayout(self.firhpfPage)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.endofHpfStopBandLabel = QtGui.QLabel(self.firhpfPage)
        self.endofHpfStopBandLabel.setObjectName(_fromUtf8("endofHpfStopBandLabel"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.endofHpfStopBandLabel)
        self.endofHpfStopBandEdit = QtGui.QLineEdit(self.firhpfPage)
        self.endofHpfStopBandEdit.setObjectName(_fromUtf8("endofHpfStopBandEdit"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.endofHpfStopBandEdit)
        self.startofHpfPassBandLabel = QtGui.QLabel(self.firhpfPage)
        self.startofHpfPassBandLabel.setObjectName(_fromUtf8("startofHpfPassBandLabel"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.startofHpfPassBandLabel)
        self.startofHpfPassBandEdit = QtGui.QLineEdit(self.firhpfPage)
        self.startofHpfPassBandEdit.setObjectName(_fromUtf8("startofHpfPassBandEdit"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.startofHpfPassBandEdit)
        self.hpfStopBandAttenLabel = QtGui.QLabel(self.firhpfPage)
        self.hpfStopBandAttenLabel.setObjectName(_fromUtf8("hpfStopBandAttenLabel"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.hpfStopBandAttenLabel)
        self.hpfStopBandAttenEdit = QtGui.QLineEdit(self.firhpfPage)
        self.hpfStopBandAttenEdit.setObjectName(_fromUtf8("hpfStopBandAttenEdit"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.hpfStopBandAttenEdit)
        self.hpfPassBandRippleLabel = QtGui.QLabel(self.firhpfPage)
        self.hpfPassBandRippleLabel.setObjectName(_fromUtf8("hpfPassBandRippleLabel"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.hpfPassBandRippleLabel)
        self.hpfPassBandRippleEdit = QtGui.QLineEdit(self.firhpfPage)
        self.hpfPassBandRippleEdit.setObjectName(_fromUtf8("hpfPassBandRippleEdit"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.hpfPassBandRippleEdit)
        self.filterTypeWidget.addWidget(self.firhpfPage)
        self.rrcPage = QtGui.QWidget()
        self.rrcPage.setObjectName(_fromUtf8("rrcPage"))
        self.formLayout_6 = QtGui.QFormLayout(self.rrcPage)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.rrcSymbolRateLabel = QtGui.QLabel(self.rrcPage)
        self.rrcSymbolRateLabel.setObjectName(_fromUtf8("rrcSymbolRateLabel"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.rrcSymbolRateLabel)
        self.rrcAlphaLabel = QtGui.QLabel(self.rrcPage)
        self.rrcAlphaLabel.setObjectName(_fromUtf8("rrcAlphaLabel"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.LabelRole, self.rrcAlphaLabel)
        self.rrcNumTapsLabel = QtGui.QLabel(self.rrcPage)
        self.rrcNumTapsLabel.setObjectName(_fromUtf8("rrcNumTapsLabel"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.LabelRole, self.rrcNumTapsLabel)
        self.rrcSymbolRateEdit = QtGui.QLineEdit(self.rrcPage)
        self.rrcSymbolRateEdit.setObjectName(_fromUtf8("rrcSymbolRateEdit"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.rrcSymbolRateEdit)
        self.rrcAlphaEdit = QtGui.QLineEdit(self.rrcPage)
        self.rrcAlphaEdit.setObjectName(_fromUtf8("rrcAlphaEdit"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.FieldRole, self.rrcAlphaEdit)
        self.rrcNumTapsEdit = QtGui.QLineEdit(self.rrcPage)
        self.rrcNumTapsEdit.setObjectName(_fromUtf8("rrcNumTapsEdit"))
        self.formLayout_6.setWidget(2, QtGui.QFormLayout.FieldRole, self.rrcNumTapsEdit)
        self.filterTypeWidget.addWidget(self.rrcPage)
        self.gausPage = QtGui.QWidget()
        self.gausPage.setObjectName(_fromUtf8("gausPage"))
        self.formLayout_7 = QtGui.QFormLayout(self.gausPage)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.gausSymbolRateLabel = QtGui.QLabel(self.gausPage)
        self.gausSymbolRateLabel.setObjectName(_fromUtf8("gausSymbolRateLabel"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.LabelRole, self.gausSymbolRateLabel)
        self.gausSymbolRateEdit = QtGui.QLineEdit(self.gausPage)
        self.gausSymbolRateEdit.setObjectName(_fromUtf8("gausSymbolRateEdit"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.gausSymbolRateEdit)
        self.gausBTLabel = QtGui.QLabel(self.gausPage)
        self.gausBTLabel.setObjectName(_fromUtf8("gausBTLabel"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.LabelRole, self.gausBTLabel)
        self.gausBTEdit = QtGui.QLineEdit(self.gausPage)
        self.gausBTEdit.setObjectName(_fromUtf8("gausBTEdit"))
        self.formLayout_7.setWidget(1, QtGui.QFormLayout.FieldRole, self.gausBTEdit)
        self.gausNumTapsLabel = QtGui.QLabel(self.gausPage)
        self.gausNumTapsLabel.setObjectName(_fromUtf8("gausNumTapsLabel"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.LabelRole, self.gausNumTapsLabel)
        self.gausNumTapsEdit = QtGui.QLineEdit(self.gausPage)
        self.gausNumTapsEdit.setObjectName(_fromUtf8("gausNumTapsEdit"))
        self.formLayout_7.setWidget(2, QtGui.QFormLayout.FieldRole, self.gausNumTapsEdit)
        self.filterTypeWidget.addWidget(self.gausPage)
        self.verticalLayout.addWidget(self.filterTypeWidget)
        self.filterPropsBox = QtGui.QGroupBox(self.filterFrame)
        self.filterPropsBox.setObjectName(_fromUtf8("filterPropsBox"))
        self.formLayout_8 = QtGui.QFormLayout(self.filterPropsBox)
        self.formLayout_8.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_8.setObjectName(_fromUtf8("formLayout_8"))
        self.nTapsLabel = QtGui.QLabel(self.filterPropsBox)
        self.nTapsLabel.setMinimumSize(QtCore.QSize(150, 0))
        self.nTapsLabel.setObjectName(_fromUtf8("nTapsLabel"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.LabelRole, self.nTapsLabel)
        self.nTapsEdit = QtGui.QLabel(self.filterPropsBox)
        self.nTapsEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.nTapsEdit.setFrameShape(QtGui.QFrame.Box)
        self.nTapsEdit.setFrameShadow(QtGui.QFrame.Raised)
        self.nTapsEdit.setText(_fromUtf8(""))
        self.nTapsEdit.setObjectName(_fromUtf8("nTapsEdit"))
        self.formLayout_8.setWidget(1, QtGui.QFormLayout.FieldRole, self.nTapsEdit)
        self.verticalLayout.addWidget(self.filterPropsBox)
        self.sysParamsBox = QtGui.QGroupBox(self.filterFrame)
        self.sysParamsBox.setObjectName(_fromUtf8("sysParamsBox"))
        self.formLayout_4 = QtGui.QFormLayout(self.sysParamsBox)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.nfftEdit = QtGui.QLineEdit(self.sysParamsBox)
        self.nfftEdit.setObjectName(_fromUtf8("nfftEdit"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.nfftEdit)
        self.nfftLabel = QtGui.QLabel(self.sysParamsBox)
        self.nfftLabel.setMinimumSize(QtCore.QSize(150, 0))
        self.nfftLabel.setObjectName(_fromUtf8("nfftLabel"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.nfftLabel)
        self.verticalLayout.addWidget(self.sysParamsBox)
        self.designButton = QtGui.QPushButton(self.filterFrame)
        self.designButton.setMinimumSize(QtCore.QSize(0, 0))
        self.designButton.setMaximumSize(QtCore.QSize(200, 16777215))
        self.designButton.setAutoDefault(True)
        self.designButton.setDefault(True)
        self.designButton.setObjectName(_fromUtf8("designButton"))
        self.verticalLayout.addWidget(self.designButton)
        self.gridLayout.addWidget(self.filterFrame, 0, 0, 1, 1)
        self.splitter = QtGui.QSplitter(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMinimumSize(QtCore.QSize(600, 0))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.tabGroup = QtGui.QTabWidget(self.splitter)
        self.tabGroup.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabGroup.sizePolicy().hasHeightForWidth())
        self.tabGroup.setSizePolicy(sizePolicy)
        self.tabGroup.setTabsClosable(False)
        self.tabGroup.setMovable(False)
        self.tabGroup.setObjectName(_fromUtf8("tabGroup"))
        self.freqTab = QtGui.QWidget()
        self.freqTab.setObjectName(_fromUtf8("freqTab"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.freqTab)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.freqPlot = Qwt5.QwtPlot(self.freqTab)
        self.freqPlot.setObjectName(_fromUtf8("freqPlot"))
        self.horizontalLayout_2.addWidget(self.freqPlot)
        self.tabGroup.addTab(self.freqTab, _fromUtf8(""))
        self.timeTab = QtGui.QWidget()
        self.timeTab.setObjectName(_fromUtf8("timeTab"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.timeTab)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.timePlot = Qwt5.QwtPlot(self.timeTab)
        self.timePlot.setObjectName(_fromUtf8("timePlot"))
        self.horizontalLayout.addWidget(self.timePlot)
        self.tabGroup.addTab(self.timeTab, _fromUtf8(""))
        self.phaseTab = QtGui.QWidget()
        self.phaseTab.setObjectName(_fromUtf8("phaseTab"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.phaseTab)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.phasePlot = Qwt5.QwtPlot(self.phaseTab)
        self.phasePlot.setObjectName(_fromUtf8("phasePlot"))
        self.horizontalLayout_3.addWidget(self.phasePlot)
        self.tabGroup.addTab(self.phaseTab, _fromUtf8(""))
        self.groupTab = QtGui.QWidget()
        self.groupTab.setObjectName(_fromUtf8("groupTab"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupTab)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.groupPlot = Qwt5.QwtPlot(self.groupTab)
        self.groupPlot.setObjectName(_fromUtf8("groupPlot"))
        self.horizontalLayout_4.addWidget(self.groupPlot)
        self.tabGroup.addTab(self.groupTab, _fromUtf8(""))
        self.overlayTab = QtGui.QWidget()
        self.overlayTab.setObjectName(_fromUtf8("overlayTab"))
        self.overlayPlot = Qwt5.QwtPlot(self.overlayTab)
        self.overlayPlot.setGeometry(QtCore.QRect(10, 10, 591, 291))
        self.overlayPlot.setObjectName(_fromUtf8("overlayPlot"))
        self.tabGroup.addTab(self.overlayTab, _fromUtf8(""))
        self.filterspecView = QtGui.QTabWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterspecView.sizePolicy().hasHeightForWidth())
        self.filterspecView.setSizePolicy(sizePolicy)
        self.filterspecView.setMinimumSize(QtCore.QSize(0, 100))
        self.filterspecView.setBaseSize(QtCore.QSize(0, 100))
        self.filterspecView.setDocumentMode(False)
        self.filterspecView.setTabsClosable(False)
        self.filterspecView.setObjectName(_fromUtf8("filterspecView"))
        self.bandDiagram = QtGui.QWidget()
        self.bandDiagram.setObjectName(_fromUtf8("bandDiagram"))
        self.gridLayout_2 = QtGui.QGridLayout(self.bandDiagram)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.bandView = BandGraphicsView(self.bandDiagram)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bandView.sizePolicy().hasHeightForWidth())
        self.bandView.setSizePolicy(sizePolicy)
        self.bandView.setMinimumSize(QtCore.QSize(400, 250))
        self.bandView.setObjectName(_fromUtf8("bandView"))
        self.gridLayout_2.addWidget(self.bandView, 0, 0, 1, 1)
        self.filterspecView.addTab(self.bandDiagram, _fromUtf8(""))
        self.poleZero = QtGui.QWidget()
        self.poleZero.setAutoFillBackground(False)
        self.poleZero.setObjectName(_fromUtf8("poleZero"))
        self.pzView = QtGui.QGraphicsView(self.poleZero)
        self.pzView.setGeometry(QtCore.QRect(10, 10, 591, 251))
        self.pzView.setObjectName(_fromUtf8("pzView"))
        self.filterspecView.addTab(self.poleZero, _fromUtf8(""))
        self.filterCoeff = QtGui.QWidget()
        self.filterCoeff.setObjectName(_fromUtf8("filterCoeff"))
        self.filterspecView.addTab(self.filterCoeff, _fromUtf8(""))
        self.gridLayout.addWidget(self.splitter, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1124, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu_File = QtGui.QMenu(self.menubar)
        self.menu_File.setObjectName(_fromUtf8("menu_File"))
        self.menu_Analysis = QtGui.QMenu(self.menubar)
        self.menu_Analysis.setObjectName(_fromUtf8("menu_Analysis"))
        self.menuMode = QtGui.QMenu(self.menu_Analysis)
        self.menuMode.setObjectName(_fromUtf8("menuMode"))
        self.menuWidgets = QtGui.QMenu(self.menubar)
        self.menuWidgets.setObjectName(_fromUtf8("menuWidgets"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.action_exit = QtGui.QAction(MainWindow)
        self.action_exit.setObjectName(_fromUtf8("action_exit"))
        self.action_save = QtGui.QAction(MainWindow)
        self.action_save.setObjectName(_fromUtf8("action_save"))
        self.action_open = QtGui.QAction(MainWindow)
        self.action_open.setObjectName(_fromUtf8("action_open"))
        self.actionMagnitude_Response = QtGui.QAction(MainWindow)
        self.actionMagnitude_Response.setCheckable(True)
        self.actionMagnitude_Response.setChecked(True)
        self.actionMagnitude_Response.setObjectName(_fromUtf8("actionMagnitude_Response"))
        self.actionPhase_Respone = QtGui.QAction(MainWindow)
        self.actionPhase_Respone.setCheckable(True)
        self.actionPhase_Respone.setObjectName(_fromUtf8("actionPhase_Respone"))
        self.actionGroup_Delay = QtGui.QAction(MainWindow)
        self.actionGroup_Delay.setCheckable(True)
        self.actionGroup_Delay.setObjectName(_fromUtf8("actionGroup_Delay"))
        self.actionPhase_Delay = QtGui.QAction(MainWindow)
        self.actionPhase_Delay.setCheckable(True)
        self.actionPhase_Delay.setObjectName(_fromUtf8("actionPhase_Delay"))
        self.actionImpulse_Response = QtGui.QAction(MainWindow)
        self.actionImpulse_Response.setCheckable(True)
        self.actionImpulse_Response.setObjectName(_fromUtf8("actionImpulse_Response"))
        self.actionStep_Response = QtGui.QAction(MainWindow)
        self.actionStep_Response.setCheckable(True)
        self.actionStep_Response.setObjectName(_fromUtf8("actionStep_Response"))
        self.actionPole_Zero_Plot = QtGui.QAction(MainWindow)
        self.actionPole_Zero_Plot.setObjectName(_fromUtf8("actionPole_Zero_Plot"))
        self.actionGrid = QtGui.QAction(MainWindow)
        self.actionGrid.setObjectName(_fromUtf8("actionGrid"))
        self.actionPole_Zero_Plot_2 = QtGui.QAction(MainWindow)
        self.actionPole_Zero_Plot_2.setCheckable(True)
        self.actionPole_Zero_Plot_2.setObjectName(_fromUtf8("actionPole_Zero_Plot_2"))
        self.actionIdeal_Band = QtGui.QAction(MainWindow)
        self.actionIdeal_Band.setCheckable(True)
        self.actionIdeal_Band.setObjectName(_fromUtf8("actionIdeal_Band"))
        self.actionGrid_2 = QtGui.QAction(MainWindow)
        self.actionGrid_2.setCheckable(True)
        self.actionGrid_2.setChecked(True)
        self.actionGrid_2.setObjectName(_fromUtf8("actionGrid_2"))
        self.actionGrid_3 = QtGui.QAction(MainWindow)
        self.actionGrid_3.setObjectName(_fromUtf8("actionGrid_3"))
        self.actionTabbed = QtGui.QAction(MainWindow)
        self.actionTabbed.setCheckable(True)
        self.actionTabbed.setObjectName(_fromUtf8("actionTabbed"))
        self.actionOverlay = QtGui.QAction(MainWindow)
        self.actionOverlay.setCheckable(True)
        self.actionOverlay.setObjectName(_fromUtf8("actionOverlay"))
        self.actionResponse_widget = QtGui.QAction(MainWindow)
        self.actionResponse_widget.setCheckable(True)
        self.actionResponse_widget.setChecked(True)
        self.actionResponse_widget.setObjectName(_fromUtf8("actionResponse_widget"))
        self.actionSpec_widget = QtGui.QAction(MainWindow)
        self.actionSpec_widget.setCheckable(True)
        self.actionSpec_widget.setChecked(True)
        self.actionSpec_widget.setObjectName(_fromUtf8("actionSpec_widget"))
        self.actionQuick_access = QtGui.QAction(MainWindow)
        self.actionQuick_access.setCheckable(True)
        self.actionQuick_access.setChecked(True)
        self.actionQuick_access.setObjectName(_fromUtf8("actionQuick_access"))
        self.actionFilter_Coefficients = QtGui.QAction(MainWindow)
        self.actionFilter_Coefficients.setObjectName(_fromUtf8("actionFilter_Coefficients"))
        self.actionDesign_widget = QtGui.QAction(MainWindow)
        self.actionDesign_widget.setCheckable(True)
        self.actionDesign_widget.setChecked(True)
        self.actionDesign_widget.setObjectName(_fromUtf8("actionDesign_widget"))
        self.menu_File.addAction(self.action_open)
        self.menu_File.addAction(self.action_save)
        self.menu_File.addAction(self.action_exit)
        self.menuMode.addAction(self.actionTabbed)
        self.menuMode.addAction(self.actionOverlay)
        self.menu_Analysis.addSeparator()
        self.menu_Analysis.addAction(self.actionMagnitude_Response)
        self.menu_Analysis.addAction(self.actionPhase_Respone)
        self.menu_Analysis.addAction(self.actionGroup_Delay)
        self.menu_Analysis.addAction(self.actionPhase_Delay)
        self.menu_Analysis.addAction(self.actionImpulse_Response)
        self.menu_Analysis.addAction(self.actionStep_Response)
        self.menu_Analysis.addAction(self.actionGrid_2)
        self.menu_Analysis.addSeparator()
        self.menu_Analysis.addAction(self.actionIdeal_Band)
        self.menu_Analysis.addAction(self.actionPole_Zero_Plot_2)
        self.menu_Analysis.addAction(self.actionFilter_Coefficients)
        self.menu_Analysis.addSeparator()
        self.menu_Analysis.addAction(self.menuMode.menuAction())
        self.menuWidgets.addAction(self.actionResponse_widget)
        self.menuWidgets.addAction(self.actionSpec_widget)
        self.menuWidgets.addAction(self.actionQuick_access)
        self.menuWidgets.addAction(self.actionDesign_widget)
        self.menubar.addAction(self.menu_File.menuAction())
        self.menubar.addAction(self.menu_Analysis.menuAction())
        self.menubar.addAction(self.menuWidgets.menuAction())

        self.retranslateUi(MainWindow)
        self.filterTypeWidget.setCurrentIndex(0)
        self.tabGroup.setCurrentIndex(0)
        self.filterspecView.setCurrentIndex(0)
        QtCore.QObject.connect(self.action_exit, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.filterTypeComboBox, self.filterDesignTypeComboBox)
        MainWindow.setTabOrder(self.filterDesignTypeComboBox, self.sampleRateEdit)
        MainWindow.setTabOrder(self.sampleRateEdit, self.filterGainEdit)
        MainWindow.setTabOrder(self.filterGainEdit, self.endofLpfPassBandEdit)
        MainWindow.setTabOrder(self.endofLpfPassBandEdit, self.startofLpfStopBandEdit)
        MainWindow.setTabOrder(self.startofLpfStopBandEdit, self.lpfStopBandAttenEdit)
        MainWindow.setTabOrder(self.lpfStopBandAttenEdit, self.lpfPassBandRippleEdit)
        MainWindow.setTabOrder(self.lpfPassBandRippleEdit, self.startofBpfPassBandEdit)
        MainWindow.setTabOrder(self.startofBpfPassBandEdit, self.endofBpfPassBandEdit)
        MainWindow.setTabOrder(self.endofBpfPassBandEdit, self.bpfTransitionEdit)
        MainWindow.setTabOrder(self.bpfTransitionEdit, self.bpfStopBandAttenEdit)
        MainWindow.setTabOrder(self.bpfStopBandAttenEdit, self.bpfPassBandRippleEdit)
        MainWindow.setTabOrder(self.bpfPassBandRippleEdit, self.startofBnfStopBandEdit)
        MainWindow.setTabOrder(self.startofBnfStopBandEdit, self.endofBnfStopBandEdit)
        MainWindow.setTabOrder(self.endofBnfStopBandEdit, self.bnfTransitionEdit)
        MainWindow.setTabOrder(self.bnfTransitionEdit, self.bnfStopBandAttenEdit)
        MainWindow.setTabOrder(self.bnfStopBandAttenEdit, self.bnfPassBandRippleEdit)
        MainWindow.setTabOrder(self.bnfPassBandRippleEdit, self.endofHpfStopBandEdit)
        MainWindow.setTabOrder(self.endofHpfStopBandEdit, self.startofHpfPassBandEdit)
        MainWindow.setTabOrder(self.startofHpfPassBandEdit, self.hpfStopBandAttenEdit)
        MainWindow.setTabOrder(self.hpfStopBandAttenEdit, self.hpfPassBandRippleEdit)
        MainWindow.setTabOrder(self.hpfPassBandRippleEdit, self.rrcSymbolRateEdit)
        MainWindow.setTabOrder(self.rrcSymbolRateEdit, self.rrcAlphaEdit)
        MainWindow.setTabOrder(self.rrcAlphaEdit, self.rrcNumTapsEdit)
        MainWindow.setTabOrder(self.rrcNumTapsEdit, self.gausSymbolRateEdit)
        MainWindow.setTabOrder(self.gausSymbolRateEdit, self.gausBTEdit)
        MainWindow.setTabOrder(self.gausBTEdit, self.gausNumTapsEdit)
        MainWindow.setTabOrder(self.gausNumTapsEdit, self.nfftEdit)
        MainWindow.setTabOrder(self.nfftEdit, self.designButton)
        MainWindow.setTabOrder(self.designButton, self.tabGroup)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "GNU Radio Filter Design Tool", None, QtGui.QApplication.UnicodeUTF8))
        self.responseBox.setTitle(QtGui.QApplication.translate("MainWindow", "Filter Responses", None, QtGui.QApplication.UnicodeUTF8))
        self.checkOverlaymode.setText(QtGui.QApplication.translate("MainWindow", "Overlay Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.checkMagres.setText(QtGui.QApplication.translate("MainWindow", "Magnitude Response", None, QtGui.QApplication.UnicodeUTF8))
        self.checkPhase.setText(QtGui.QApplication.translate("MainWindow", "Phase Response", None, QtGui.QApplication.UnicodeUTF8))
        self.checkGdelay.setText(QtGui.QApplication.translate("MainWindow", "Group Delay", None, QtGui.QApplication.UnicodeUTF8))
        self.checkPdelay.setText(QtGui.QApplication.translate("MainWindow", "Phase Delay", None, QtGui.QApplication.UnicodeUTF8))
        self.checkImpulse.setText(QtGui.QApplication.translate("MainWindow", "Impulse Response", None, QtGui.QApplication.UnicodeUTF8))
        self.checkStep.setText(QtGui.QApplication.translate("MainWindow", "Step Response", None, QtGui.QApplication.UnicodeUTF8))
        self.checkGrid.setText(QtGui.QApplication.translate("MainWindow", "Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.groupSpecs.setTitle(QtGui.QApplication.translate("MainWindow", "Filter Specs", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBand.setText(QtGui.QApplication.translate("MainWindow", "Ideal Band", None, QtGui.QApplication.UnicodeUTF8))
        self.checkPzplot.setText(QtGui.QApplication.translate("MainWindow", "Pole-Zero Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.checkFcoeff.setText(QtGui.QApplication.translate("MainWindow", "Filter Coefficients", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "FIR", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "IIR", None, QtGui.QApplication.UnicodeUTF8))
        self.filterTypeComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Low Pass", None, QtGui.QApplication.UnicodeUTF8))
        self.filterTypeComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Band Pass", None, QtGui.QApplication.UnicodeUTF8))
        self.filterTypeComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Complex Band Pass", None, QtGui.QApplication.UnicodeUTF8))
        self.filterTypeComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "Band Notch", None, QtGui.QApplication.UnicodeUTF8))
        self.filterTypeComboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "High Pass", None, QtGui.QApplication.UnicodeUTF8))
        self.filterTypeComboBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "Root Raised Cosine", None, QtGui.QApplication.UnicodeUTF8))
        self.filterTypeComboBox.setItemText(6, QtGui.QApplication.translate("MainWindow", "Gaussian", None, QtGui.QApplication.UnicodeUTF8))
        self.filterDesignTypeComboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "Hamming Window", None, QtGui.QApplication.UnicodeUTF8))
        self.filterDesignTypeComboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "Hann Window", None, QtGui.QApplication.UnicodeUTF8))
        self.filterDesignTypeComboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "Blackman Window", None, QtGui.QApplication.UnicodeUTF8))
        self.filterDesignTypeComboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "Rectangular Window", None, QtGui.QApplication.UnicodeUTF8))
        self.filterDesignTypeComboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "Kaiser Window", None, QtGui.QApplication.UnicodeUTF8))
        self.filterDesignTypeComboBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "Blackman-harris Window", None, QtGui.QApplication.UnicodeUTF8))
        self.filterDesignTypeComboBox.setItemText(6, QtGui.QApplication.translate("MainWindow", "Equiripple", None, QtGui.QApplication.UnicodeUTF8))
        self.sampleRateLabel.setText(QtGui.QApplication.translate("MainWindow", "Sample Rate (sps)", None, QtGui.QApplication.UnicodeUTF8))
        self.filterGainLabel.setText(QtGui.QApplication.translate("MainWindow", "Filter Gain", None, QtGui.QApplication.UnicodeUTF8))
        self.endofLpfPassBandLabel.setText(QtGui.QApplication.translate("MainWindow", "End of Pass Band (Hz)", None, QtGui.QApplication.UnicodeUTF8))
        self.startofLpfStopBandLabel.setText(QtGui.QApplication.translate("MainWindow", "Start of Stop Band (Hz)", None, QtGui.QApplication.UnicodeUTF8))
        self.lpfStopBandAttenLabel.setText(QtGui.QApplication.translate("MainWindow", "Stop Band Attenuation (dB)", None, QtGui.QApplication.UnicodeUTF8))
        self.lpfPassBandRippleLabel.setText(QtGui.QApplication.translate("MainWindow", "Pass Band Ripple (dB)", None, QtGui.QApplication.UnicodeUTF8))
        self.startofBpfPassBandLabel.setText(QtGui.QApplication.translate("MainWindow", "Start of Pass Band (Hz)", None, QtGui.QApplication.UnicodeUTF8))
        self.endofBpfPassBandLabel.setText(QtGui.QApplication.translate("MainWindow", "End of Pass Band (Hz)", None, QtGui.QApplication.UnicodeUTF8))
        self.bpfStopBandAttenLabel.setText(QtGui.QApplication.translate("MainWindow", "Stop Band Attenuation (dB)", None, QtGui.QApplication.UnicodeUTF8))
        self.bpfTransitionLabel.setText(QtGui.QApplication.translate("MainWindow", "Transition Width (Hz)", None, QtGui.QApplication.UnicodeUTF8))
        self.bpfPassBandRippleLabel.setText(QtGui.QApplication.translate("MainWindow", "Pass Band Ripple (dB)", None, QtGui.QApplication.UnicodeUTF8))
        self.startofBnfStopBandLabel.setText(QtGui.QApplication.translate("MainWindow", "Start of Stop Band (Hz)", None, QtGui.QApplication.UnicodeUTF8))
        self.endofBnfStopBandLabel.setText(QtGui.QApplication.translate("MainWindow", "End of Stop Band (Hz)", None, QtGui.QApplication.UnicodeUTF8))
        self.bnfTransitionLabel.setText(QtGui.QApplication.translate("MainWindow", "Transition Width (Hz)", None, QtGui.QApplication.UnicodeUTF8))
        self.bnfStopBandAttenLabel.setText(QtGui.QApplication.translate("MainWindow", "Stop Band Attenuation (dB)", None, QtGui.QApplication.UnicodeUTF8))
        self.bnfPassBandRippleLabel.setText(QtGui.QApplication.translate("MainWindow", "Pass Band Ripple (dB)", None, QtGui.QApplication.UnicodeUTF8))
        self.endofHpfStopBandLabel.setText(QtGui.QApplication.translate("MainWindow", "End of Stop Band (Hz)", None, QtGui.QApplication.UnicodeUTF8))
        self.startofHpfPassBandLabel.setText(QtGui.QApplication.translate("MainWindow", "Start of Pass Band (Hz)", None, QtGui.QApplication.UnicodeUTF8))
        self.hpfStopBandAttenLabel.setText(QtGui.QApplication.translate("MainWindow", "Stop Band Attenuation (dB)", None, QtGui.QApplication.UnicodeUTF8))
        self.hpfPassBandRippleLabel.setText(QtGui.QApplication.translate("MainWindow", "Pass Band Ripple (dB)", None, QtGui.QApplication.UnicodeUTF8))
        self.rrcSymbolRateLabel.setText(QtGui.QApplication.translate("MainWindow", "Symbol Rate (sps)", None, QtGui.QApplication.UnicodeUTF8))
        self.rrcAlphaLabel.setText(QtGui.QApplication.translate("MainWindow", "Roll-off Factor", None, QtGui.QApplication.UnicodeUTF8))
        self.rrcNumTapsLabel.setText(QtGui.QApplication.translate("MainWindow", "Number of Taps", None, QtGui.QApplication.UnicodeUTF8))
        self.gausSymbolRateLabel.setText(QtGui.QApplication.translate("MainWindow", "Symbol Rate (sps)", None, QtGui.QApplication.UnicodeUTF8))
        self.gausBTLabel.setText(QtGui.QApplication.translate("MainWindow", "Roll-off Factor", None, QtGui.QApplication.UnicodeUTF8))
        self.gausNumTapsLabel.setText(QtGui.QApplication.translate("MainWindow", "Number of Taps", None, QtGui.QApplication.UnicodeUTF8))
        self.filterPropsBox.setTitle(QtGui.QApplication.translate("MainWindow", "Filter Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.nTapsLabel.setText(QtGui.QApplication.translate("MainWindow", "Number of Taps:", None, QtGui.QApplication.UnicodeUTF8))
        self.sysParamsBox.setTitle(QtGui.QApplication.translate("MainWindow", "System Parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.nfftLabel.setText(QtGui.QApplication.translate("MainWindow", "Num FFT points", None, QtGui.QApplication.UnicodeUTF8))
        self.designButton.setText(QtGui.QApplication.translate("MainWindow", "Design", None, QtGui.QApplication.UnicodeUTF8))
        self.tabGroup.setTabText(self.tabGroup.indexOf(self.freqTab), QtGui.QApplication.translate("MainWindow", "Magnitude Response", None, QtGui.QApplication.UnicodeUTF8))
        self.tabGroup.setTabText(self.tabGroup.indexOf(self.timeTab), QtGui.QApplication.translate("MainWindow", "Time Domain", None, QtGui.QApplication.UnicodeUTF8))
        self.tabGroup.setTabText(self.tabGroup.indexOf(self.phaseTab), QtGui.QApplication.translate("MainWindow", "Phase", None, QtGui.QApplication.UnicodeUTF8))
        self.tabGroup.setTabText(self.tabGroup.indexOf(self.groupTab), QtGui.QApplication.translate("MainWindow", "Group Delay", None, QtGui.QApplication.UnicodeUTF8))
        self.tabGroup.setTabText(self.tabGroup.indexOf(self.overlayTab), QtGui.QApplication.translate("MainWindow", "Overlay ", None, QtGui.QApplication.UnicodeUTF8))
        self.filterspecView.setTabText(self.filterspecView.indexOf(self.bandDiagram), QtGui.QApplication.translate("MainWindow", "Ideal Band", None, QtGui.QApplication.UnicodeUTF8))
        self.filterspecView.setTabText(self.filterspecView.indexOf(self.poleZero), QtGui.QApplication.translate("MainWindow", "Pole-Zero Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.filterspecView.setTabText(self.filterspecView.indexOf(self.filterCoeff), QtGui.QApplication.translate("MainWindow", "Filter Coefficients", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_File.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Analysis.setTitle(QtGui.QApplication.translate("MainWindow", "Analysis", None, QtGui.QApplication.UnicodeUTF8))
        self.menuMode.setTitle(QtGui.QApplication.translate("MainWindow", "Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.menuWidgets.setTitle(QtGui.QApplication.translate("MainWindow", "Widgets", None, QtGui.QApplication.UnicodeUTF8))
        self.action_exit.setText(QtGui.QApplication.translate("MainWindow", "E&xit", None, QtGui.QApplication.UnicodeUTF8))
        self.action_save.setText(QtGui.QApplication.translate("MainWindow", "&Save", None, QtGui.QApplication.UnicodeUTF8))
        self.action_save.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open.setText(QtGui.QApplication.translate("MainWindow", "&Open", None, QtGui.QApplication.UnicodeUTF8))
        self.action_open.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMagnitude_Response.setText(QtGui.QApplication.translate("MainWindow", "Magnitude Response", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPhase_Respone.setText(QtGui.QApplication.translate("MainWindow", "Phase Respone", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGroup_Delay.setText(QtGui.QApplication.translate("MainWindow", "Group Delay", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPhase_Delay.setText(QtGui.QApplication.translate("MainWindow", "Phase Delay", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImpulse_Response.setText(QtGui.QApplication.translate("MainWindow", "Impulse Response", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStep_Response.setText(QtGui.QApplication.translate("MainWindow", "Step Response", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPole_Zero_Plot.setText(QtGui.QApplication.translate("MainWindow", "Pole-Zero Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGrid.setText(QtGui.QApplication.translate("MainWindow", "Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.actionPole_Zero_Plot_2.setText(QtGui.QApplication.translate("MainWindow", "Pole Zero Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.actionIdeal_Band.setText(QtGui.QApplication.translate("MainWindow", "Ideal Band", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGrid_2.setText(QtGui.QApplication.translate("MainWindow", "Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGrid_3.setText(QtGui.QApplication.translate("MainWindow", "Grid", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTabbed.setText(QtGui.QApplication.translate("MainWindow", "Tabbed", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOverlay.setText(QtGui.QApplication.translate("MainWindow", "Overlay", None, QtGui.QApplication.UnicodeUTF8))
        self.actionResponse_widget.setText(QtGui.QApplication.translate("MainWindow", "Response widget", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSpec_widget.setText(QtGui.QApplication.translate("MainWindow", "Spec widget", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuick_access.setText(QtGui.QApplication.translate("MainWindow", "Quick access", None, QtGui.QApplication.UnicodeUTF8))
        self.actionFilter_Coefficients.setText(QtGui.QApplication.translate("MainWindow", "Filter Coefficients", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDesign_widget.setText(QtGui.QApplication.translate("MainWindow", "Design widget", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import Qwt5
from bandgraphicsview import BandGraphicsView
